services:
  postgres-customer:
    container_name: postgres-customer
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ussdservice
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-customer:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-fraud:
    container_name: postgres-fraud
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ussdservice
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-fraud:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-notification:
    container_name: postgres-notification
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ussdservice
      POSTGRES_PASSWORD: password
      PGDATA: /data/notification
    volumes:
      - postgres-notification:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

#  eureka-server:
#    image: nikolajovanovic93/eureka-server
#    container_name: eureka-server
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - "8761:8761"
#    networks:
#      - spring
#    depends_on:
#      - zipkin

#  apigw:
#    image: nikolajovanovic93/apigw
#    container_name: apigw
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - "8083:8083"
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server

  notification:
    image: nikolajovanovic93/notification
    container_name: notification
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8088:8088"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres-notification
      - rabbitmq

  fraud:
    image: nikolajovanovic93/fraud
    container_name: fraud
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres-fraud

  customer:
    image: nikolajovanovic93/customer
    container_name: customer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - notification
      - fraud
      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres-customer:
    name: postgres-customer
  postgres-fraud:
    name: postgres-fraud
  postgres-notification:
    name: postgres-notification
  pgadmin:
    name: pgadmin