services:
  postgres-customer:
    container_name: postgres-customer
    image: postgres
    environment:
      POSTGRES_USER: ussdservice
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-customer:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-fraud:
    container_name: postgres-fraud
    image: postgres
    environment:
      POSTGRES_USER: ussdservice
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-fraud:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-notification:
    container_name: postgres-notification
    image: postgres
    environment:
      POSTGRES_USER: ussdservice
      POSTGRES_PASSWORD: password
      PGDATA: /data/notification
    volumes:
      - postgres-notification:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    name: postgres
    driver: bridge

volumes:
  postgres-customer:
    name: postgres-customer
  postgres-fraud:
    name: postgres-fraud
  postgres-notification:
    name: postgres-notification
  pgadmin:
    name: pgadmin