server:
  port: 8088

spring:
  application:
    name: notification
  datasource:
    password: password
    url: jdbc:postgresql://postgres-notification:5432/notification
    username: ussdservice
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  zipkin:
    base-url: http://zipkin:9411

  rabbitmq:
    addresses: rabbitmq:5672

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

notification:
  default:
    subject: USSD service platform registration
    sender: noreply@ussdservices.com